### ISSUE TITLE
Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8'

### ISSUE THREAD

**Issue by alerosmile** [eclipse-ee4j/eclipselink#1119]
Indention is not working if encoding is set to 'UTF-8' (not 'utf-8') and a custom CharacterEscapeHandler is installed. The bug is in method OutputStreamRecord.writeValue(String, boolean, boolean, OutputStream). This method does not write to the given Outputstream. Instead it writes directly to the underlying buffer. This way the tab buffer in FormattedOutputStreamRecord.tab() remains empty.

**Comment by rfelcman** [comment]
Hello,

this is just workaround before this bug will be fixed, but if You need some functional solution it's possible use JAXB API way.

See e.g.
```
...
System.setProperty(JAXBContext.JAXB_CONTEXT_FACTORY, "org.eclipse.persistence.jaxb.JAXBContextFactory");
final HashMap<String, Object> contextProperties = new HashMap<>();
contextProperties.put(JAXBContextProperties.MEDIA_TYPE, "application/xml");
jaxbContext = JAXBContext.newInstance(DOMAIN_CLASSES, contextProperties);

//Unmarshall
Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
Object unmarshallDoc = unmarshaller.unmarshal(Thread.currentThread().getContextClassLoader().getResource(XML_READ_DOCUMENT));

//Marshall  (JAXB API)
ByteArrayOutputStream byteArrayOutputStream1 = new ByteArrayOutputStream();
Writer writer = new OutputStreamWriter(byteArrayOutputStream1, "UTF-8");
Marshaller marshaller1 = jaxbContext.createMarshaller();
CharacterEscapeHandler handler1 = new TestCharacterEscapeHandler();
marshaller1.setProperty(MarshallerProperties.CHARACTER_ESCAPE_HANDLER, handler1);
marshaller1.marshal(unmarshallDoc, writer);
...
```

```
package com.oracle.moxy.bugtest.domain;

import org.eclipse.persistence.oxm.CharacterEscapeHandler;

import java.io.IOException;
import java.io.Writer;

public class TestCharacterEscapeHandler implements CharacterEscapeHandler {

    @Override
    public void escape(char[] buf, int start, int len, boolean isAttValue, Writer out) throws IOException {
        for (int i = start; i < start + len; i++) {
            char ch = buf[i];

            if (ch == '%') {
                out.write("*");
                continue;
            }

            out.write(ch);
        }
    }
}

```

**Comment by rfelcman** [comment]
[2.7] Bugfix for - Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8 - backport from master #1156

**Comment by rfelcman** [comment]
Fixed in master, 3.0, 2.7 branches. Will be available for testing from the Nightly builds page https://www.eclipse.org/eclipselink/downloads/nightly.php or as a Maven snapshot from https://jakarta.oss.sonatype.org/content/repositories/snapshots/org/eclipse/persistence/ .
Will be included in the next release.

**Comment by alerosmile** [comment]
I cannot test it. org.eclipse.persistence.core:2.7.9-SNAPSHOT (jar) depends on org.eclipse.persistence.asm 9.1.0 which cannot be found.

**Comment by lukasj** [comment]
that is available in staging repo, see https://wiki.eclipse.org/EclipseLink/Maven for set up

**Comment by alerosmile** [comment]
> that is available in staging repo, see https://wiki.eclipse.org/EclipseLink/Maven for set up

Thanks. I got it working...

But the bug is not fixed yet. The ByteArrayOutputStream baos in method FormattedOutputStreamRecord.tab() still remains empty if a custom CharacterEscapeHandler is set.

**Comment by rfelcman** [comment]
Sorry, but could You please provide there test reproducer. As an example there is attached my test project (against 3.1.0-SNAPSHOT `jakarta.xml.bind.*` packages instead of `javax.xml.bind.*`. Most important class there is `com.oracle.moxy.bugtest.TestBug`and methods the `moxyXmlDocTestELAPI()` - based on EL API and `moxyXmlDocTestJAXBAPI()` - based on JAXB API.
Another example is test `XMLMarshalTestCases.java testMarshalWithCharacterEscapeHandlerToFormattedOutputStreamRecord();`in PR #1156 .

[moxy-bug-1119-IndentionNotWorkingIfCustomCharacterEscapeHandlerIsSetAndEncodingIsSetToUTF-8.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/6551883/moxy-bug-1119-IndentionNotWorkingIfCustomCharacterEscapeHandlerIsSetAndEncodingIsSetToUTF-8.tar.gz)
