### ISSUE TITLE
All functions introduced in JPA 3.1 dose not work in JPQL

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/eclipselink#1583]
I started a new repository [Jakarta EE 10 Sandbox](https://github.com/hantsy/jakartaee10-sandbox/) to experience the new Jakarta EE 10 features.

I was using Glassfish 7.0 M6(which shipped with the latest EclipseLinks) and Java 17.

Unluckily, [all of the new functions introduced in JPA 3.1](https://newsroom.eclipse.org/eclipse-newsletter/2022/march/what%E2%80%99s-new-jakarta-persistence-31) did not work.
 
Similar to #1554, I have encountered similar issues in the literal JPQL query. 

Check my example tests to reproduce it, https://github.com/hantsy/jakartaee10-sandbox/blob/master/jpa/src/test/java/com/example/it/JPQLFunctionsTest.java

There are 3 tests to run the numeric functions, new date time functions, and `extract` functions, none of them are working well with Glassfish 7.0 M6/Java 17.

Attached a copy the Glassfish logs.
[server.log](https://github.com/eclipse-ee4j/eclipselink/files/9086076/server.log)

**BTW, I have tried these functions in literal JPQL queries with the latest Hibernate 6.1.1.Final, all work as expected, check my Hibernate 6 example in the same repository.**

**Comment by Tomas-Kraus** [comment]
Looks like this has the same cause as issue #1593 - Eclipselink was not updated in GF. You have to wait for next EclipseLink release.

**Comment by hantsy** [comment]
Still failed in Glassfish 7.0.0-M8, 
[server.log](https://github.com/eclipse-ee4j/eclipselink/files/9423657/server.log)

**Comment by lukasj** [comment]
Did eclipselink version in GF change? that is the only way to see it fixed there (unless one manually updates jars there)

**Comment by hantsy** [comment]
See: https://github.com/eclipse-ee4j/glassfish/blob/7.0.0-M8/appserver/pom.xml#L113

**Comment by lukasj** [comment]
Is that different from M7?

**Comment by pzygielo** [comment]
GF 7.0.0-M10 uses the latest 4.0.0 EL:
https://github.com/eclipse-ee4j/glassfish/blob/a44106a9509a9076338b8e880c73b4d2d94b7bc0/appserver/pom.xml#L109 and with Derby 10.15: https://github.com/eclipse-ee4j/glassfish/blob/a44106a9509a9076338b8e880c73b4d2d94b7bc0/appserver/pom.xml#L179 we get
```
Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202210051929): org.eclipse.persistence.exceptions.DatabaseException
 Internal Exception: java.sql.SQLSyntaxErrorException: 'WEEK' is not recognized as a function or procedure.
 Error Code: 20000
 Call: SELECT NAME, YEAR(BIRTHDATE), ((MONTH(BIRTHDATE)+2)/3), MONTH(BIRTHDATE), WEEK(BIRTHDATE), DAY(BIRTHDATE), HOUR(BIRTHDATE), MINUTE(BIRTHDATE), CAST(SECOND(BIRTHDATE) AS FLOAT) FROM PERSON
 Query: ReportQuery(referenceClass=Person sql="SELECT NAME, YEAR(BIRTHDATE), ((MONTH(BIRTHDATE)+2)/3), MONTH(BIRTHDATE), WEEK(BIRTHDATE), DAY(BIRTHDATE), HOUR(BIRTHDATE), MINUTE(BIRTHDATE), CAST(SECOND(BIRTHDATE) AS FLOAT) FROM PERSON")
```

**Comment by pzygielo** [comment]
https://github.com/eclipse-ee4j/eclipselink/blob/140718fa5062562a31cdb0451ffa0bb09523047d/jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java#L491

**Comment by Tomas-Kraus** [comment]
Looks like WEEK is really missing in Derby platform.

**Comment by Tomas-Kraus** [comment]
@pzygielo it shall be fixed in master branch, please can you confirm that it works properly now?
You have to replace org.eclipse.persistence.core module with fresh master build in GF.

**Comment by rfelcman** [comment]
Nightly build is in progress now
https://ci.eclipse.org/eclipselink/job/eclipselink-nightly-master/361/
If everything will pass new snapshot will be published during 1 hour.

**Comment by pzygielo** [comment]
> If everything will pass new snapshot will be published during 1 hour.

Thank you.

**Comment by pzygielo** [comment]
WFM.
Used EL build 92 to patch GF 7.0.0-M10 and got with @hantsy's reproducer:
```
[INFO] Running com.example.it.JPQLFunctionsTest
...
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 98.852 s - in com.example.it.JPQLFunctionsTest
[INFO] Running com.example.it.UUIDStrategyTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.929 s - in com.example.it.UUIDStrategyTest
[INFO] Running com.example.it.JPQLCriteriaBuilderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.665 s - in com.example.it.JPQLCriteriaBuilderTest
...
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M7:verify (integration-test) @ jpa-examples ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:13 min
[INFO] Finished at: 2022-11-29T16:30:52+01:00
[INFO] ------------------------------------------------------------------------
```

:tada:

**Comment by hantsy** [comment]
@pzygielo But it seems there is no release includes this patch. So Glassfish 7.0.0 GA and 7.0.1 still encountered this issue.

**Comment by pzygielo** [comment]
Indeed - new EL has to be released first. Only then it can be integrated into GF.

**Comment by rfelcman** [comment]
I hope, that 4.0.1-RC1 maybe 4.0.1 (Final) will be released next week.

**Comment by hantsy** [comment]
> Indeed - new EL has to be released first. Only then it can be integrated into GF.

I have browsed the expressly project, it seems there is no updates since Aug, 2022, which version you are using to replace the existing one in GlassFish.

**Comment by pzygielo** [comment]
by EL I meant eclipselink
